name: releases-workflow.yml
on:
  release:
    types: [ published ]
env:
  DOCKER_HUB_IMAGE_ID: matlock0o/astropay:ledge-service-${{ github.sha }}

jobs:
  MainWorkflow:
    name: Main Workflow
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Java Environment
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: adopt
          architecture: x64
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.PI_BE_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.PI_BE_DOCKER_HUB_SECRET }}
      - name: Execute Test
        run: mvn clean test
      - name: Build Java Jar
        run: mvn -e clean install -DskipTests
      - name: Docker Hub Build
        run: docker build -t ${{ env.DOCKER_HUB_IMAGE_ID }} .
      - name: Push to Docker Hub
        run: docker push ${{ env.DOCKER_HUB_IMAGE_ID }}
